In [19]:
import numpy as np

In [20]:
arr1=np.random.randint(10,20,30).reshape(5,6)
print(arr1)

[[18 10 16 13 15 14]
 [11 17 15 15 14 13]
 [16 13 14 14 15 17]
 [13 11 16 19 17 11]
 [14 13 15 16 18 14]]


In [21]:
arr2=np.random.randint(30,40,30).reshape(5,6)
print(arr2)

[[33 32 32 30 39 32]
 [34 34 37 32 30 32]
 [32 36 35 39 38 30]
 [30 36 39 36 38 31]
 [35 37 34 33 33 31]]


In [22]:
arr3=arr1+arr2
print(arr3)

[[51 42 48 43 54 46]
 [45 51 52 47 44 45]
 [48 49 49 53 53 47]
 [43 47 55 55 55 42]
 [49 50 49 49 51 45]]


In [23]:
print(arr1)
print()
print(arr2)

[[18 10 16 13 15 14]
 [11 17 15 15 14 13]
 [16 13 14 14 15 17]
 [13 11 16 19 17 11]
 [14 13 15 16 18 14]]

[[33 32 32 30 39 32]
 [34 34 37 32 30 32]
 [32 36 35 39 38 30]
 [30 36 39 36 38 31]
 [35 37 34 33 33 31]]


In [24]:
arr1+=arr2    #arr1=arr1+arr2
print(arr1)

[[51 42 48 43 54 46]
 [45 51 52 47 44 45]
 [48 49 49 53 53 47]
 [43 47 55 55 55 42]
 [49 50 49 49 51 45]]


In [28]:
# Unary Operation  -- min max sum
arr1

array([[51, 42, 48, 43, 54, 46],
       [45, 51, 52, 47, 44, 45],
       [48, 49, 49, 53, 53, 47],
       [43, 47, 55, 55, 55, 42],
       [49, 50, 49, 49, 51, 45]], dtype=int32)

In [26]:
print(np.sum(arr1))

1457


In [27]:
print(np.min(arr1))

42


In [29]:
print(np.max(arr1))

55


In [30]:
print(arr1)

[[51 42 48 43 54 46]
 [45 51 52 47 44 45]
 [48 49 49 53 53 47]
 [43 47 55 55 55 42]
 [49 50 49 49 51 45]]


In [32]:
print(np.max(arr1,axis=0))

[51 51 55 55 55 47]


In [ ]:
axis=0  vertical direction(columns)
axis=1  horizantal direction(rows)

In [33]:
print(np.min(arr1,axis=1))

[42 44 47 42 45]


In [34]:
print(np.sum(arr1,axis=1))

[284 284 299 297 293]


# Indexing and slicing 

In [35]:
arr1=np.random.randint(10,20,10)
print(arr1)

[17 11 17 18 17 18 18 17 15 13]


In [37]:
print(arr1[0])
print(arr1[-1])

17
13


In [38]:
print(arr1[3:4])  # start inclusive stop exclusive

[18]


In [39]:
print(arr1[2:5])

[17 18 17]


In [40]:
print(arr1[5:1:-1])

[18 17 18 17]


In [41]:
arr1=np.random.randint(10,20,30).reshape(5,6)
print(arr1)

[[13 15 12 15 14 13]
 [17 12 12 18 12 16]
 [16 12 11 15 11 12]
 [13 14 11 10 14 15]
 [16 12 15 10 17 12]]


In [43]:
print(arr1[::])
print(arr1[::,::])

[[13 15 12 15 14 13]
 [17 12 12 18 12 16]
 [16 12 11 15 11 12]
 [13 14 11 10 14 15]
 [16 12 15 10 17 12]]
[[13 15 12 15 14 13]
 [17 12 12 18 12 16]
 [16 12 11 15 11 12]
 [13 14 11 10 14 15]
 [16 12 15 10 17 12]]


In [44]:
print(arr1)

[[13 15 12 15 14 13]
 [17 12 12 18 12 16]
 [16 12 11 15 11 12]
 [13 14 11 10 14 15]
 [16 12 15 10 17 12]]


In [47]:
print(arr1[2])

[16 12 11 15 11 12]


In [50]:
print(arr1[2][-2])

11


In [51]:
print(arr1[2,-2])

11


In [54]:
print(arr1[::,2])

[12 12 11 11 15]


In [55]:
arr1

array([[13, 15, 12, 15, 14, 13],
       [17, 12, 12, 18, 12, 16],
       [16, 12, 11, 15, 11, 12],
       [13, 14, 11, 10, 14, 15],
       [16, 12, 15, 10, 17, 12]], dtype=int32)

In [58]:
print(arr1[2::,3::])

[[15 11 12]
 [10 14 15]
 [10 17 12]]


In [ ]:
12 12

14 14

In [66]:
print(arr1[1:4:2,1:5:3])

[[12 12]
 [14 14]]


In [70]:
print(arr1[1:4:2,1:5:3])

[[12 12]
 [14 14]]


In [71]:
arr1

array([[13, 15, 12, 15, 14, 13],
       [17, 12, 12, 18, 12, 16],
       [16, 12, 11, 15, 11, 12],
       [13, 14, 11, 10, 14, 15],
       [16, 12, 15, 10, 17, 12]], dtype=int32)

In [72]:
res=arr1[0,1],arr1[4,3],arr1[2,4]
print(res)

(np.int32(15), np.int32(10), np.int32(11))


In [73]:
row_ind=[0,4,2]
col_ind=[1,3,4]
arr1[row_ind,col_ind]

array([15, 10, 11], dtype=int32)

In [74]:
fruit=np.array([["Banana","Mango","Gauva","Avacodo"],
                ["Papaya","Jack fruit","Plum","Strawberry"],
                ["Apricot","Apple","Blue Berry","Black Berry"]])
fruit

array([['Banana', 'Mango', 'Gauva', 'Avacodo'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue Berry', 'Black Berry']], dtype='<U11')

In [75]:
#0,1  1,1  1,3  2,2  ="Potato"

row_ind=[0,1,1,2]
col_ind=[1,1,3,2]
fruit[row_ind,col_ind]="Potato"
fruit

array([['Banana', 'Potato', 'Gauva', 'Avacodo'],
       ['Papaya', 'Potato', 'Plum', 'Potato'],
       ['Apricot', 'Apple', 'Potato', 'Black Berry']], dtype='<U11')

In [76]:
arr1

array([[13, 15, 12, 15, 14, 13],
       [17, 12, 12, 18, 12, 16],
       [16, 12, 11, 15, 11, 12],
       [13, 14, 11, 10, 14, 15],
       [16, 12, 15, 10, 17, 12]], dtype=int32)

In [77]:
arr1>15

array([[False, False, False, False, False, False],
       [ True, False, False,  True, False,  True],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False,  True, False]])

In [78]:
# access all the element from arr1 which are greater than 15
arr1[arr1>15]

array([17, 18, 16, 16, 16, 17], dtype=int32)

In [80]:
# count the total no of elements which are greater than 15
#len(arr1[arr1>15])
np.sum(arr1>15)

np.int64(6)

In [81]:
# get sum of all the elements which are greater than 15 along the columns
np.sum(arr1>15,axis=0)

array([3, 0, 0, 1, 1, 1])

In [82]:
arr1

array([[13, 15, 12, 15, 14, 13],
       [17, 12, 12, 18, 12, 16],
       [16, 12, 11, 15, 11, 12],
       [13, 14, 11, 10, 14, 15],
       [16, 12, 15, 10, 17, 12]], dtype=int32)

In [83]:
#np.all--Return true if all values satisfy the condn,
np.all(arr1>15)

np.False_

In [84]:
#np.any  -- return True if at least one value satisfy the condn

np.any(arr1>15)

np.True_