# Numpy

In [ ]:
What is Numpy
Numerical python

In [ ]:
Why we use numpy

python list are slower for large data
no built in mathematical operations
no memory effiencent

Numpy 
faster than list(written C)
less memory
powerful math functions
backbone of pandas, tenserflow


In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\users\administrator\anaconda3\lib\site-packages (2.1.3)



In [14]:
import numpy as np

# Array Creation

In [15]:

arr=np.array([10,20,30,40,50,60,70])
print(arr)

[10 20 30 40 50 60 70]


In [16]:
print(type(arr))

<class 'numpy.ndarray'>


In [17]:
# Array is collection of homogenoues elements
print(arr.dtype)

int64


In [18]:
# size of array
print(arr.size)

7


In [19]:
# shape of the array
print(arr.shape)

(7,)


In [20]:
# dimension of the array
print(arr.ndim)

1


In [21]:
# creating a array with hetrogenous elemetns
arr1=np.array([10,20,30,40,50,60.70])
print(arr1)

[10.  20.  30.  40.  50.  60.7]


In [22]:
print(arr1.dtype)

float64


In [23]:
arr2=np.array([10.,2.0,30.,40.,50.,60])
print(arr2)

[10.  2. 30. 40. 50. 60.]


In [24]:
# hetrogenious data
arr3=np.array([10,20,30,40,50,60.70,80+90j])
print(arr3)

[10.  +0.j 20.  +0.j 30.  +0.j 40.  +0.j 50.  +0.j 60.7 +0.j 80. +90.j]


In [25]:
print(arr3.dtype)

complex128


In [26]:
arr4=np.array([10,20,30,40,50,60.70,80+90j,'100'])
print(arr4)

['10' '20' '30' '40' '50' '60.7' '(80+90j)' '100']


In [27]:
print(arr4.dtype)

<U64


In [ ]:
#upcasting
#object
#string
#complex
#flaot
#int


In [29]:
# arrange
#arrange(start,stop,step)
# arragne can take a fraction value as step where range can take only integer values

arr1=np.arange(10,21)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20]


In [30]:
arr1=np.arange(10,21,0.5)
print(arr1)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5]


In [32]:
# linspace(start,stop, no.of elements)
# stop is inclusive
# divide number in equal parts)
arr1=np.linspace(10,20,10)
print(arr1)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [34]:
#(stop-start)/(step-1)

#20-10/(10-1)

10/9

1.1111111111111112

In [35]:
arr2=np.linspace(10,19,10)
print(arr2)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [37]:
# creating array with all element 0
arr1=np.zeros((6,))
print(arr1)

[0. 0. 0. 0. 0. 0.]


In [38]:
arr2=np.zeros((6,6))
print(arr2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [39]:
# creating array with all elements ones
arr1=np.ones((6,))
print(arr1)

[1. 1. 1. 1. 1. 1.]


In [41]:
arr2=np.ones((6,3),dtype=int)
print(arr2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [42]:
# identity array=
# diagoanl from top left to bottom right all are 1 rest are 0
#no of rows and columns should be same
arr1=np.eye(5,dtype=int)
print(arr1)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [44]:
# empty array
arr2=np.empty((7,8))
print(arr2)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 6.95301684e-310
  2.56914136e-322 1.60415017e-311 6.95301688e-310 1.60415017e-311]
 [1.60415017e-311 1.60415018e-311 1.60415017e-311 6.95301688e-310
  1.60415018e-311 6.95301688e-310 1.60415018e-311 6.95301688e-310]
 [6.95301688e-310 1.60415017e-311 1.60415017e-311 1.60414986e-311
  1.60414986e-311 6.95301688e-310 1.60415018e-311 6.95301688e-310]
 [1.60415018e-311 6.95301688e-310 6.95301688e-310 1.60415018e-311
  6.95301688e-310 1.60415018e-311 1.60414987e-311 1.60415018e-311]
 [1.60414987e-311 6.95301688e-310 6.95301688e-310 1.60415018e-311
  6.95301688e-310 1.60415018e-311 1.60415018e-311 1.60415018e-311]
 [1.60415018e-311 1.60415018e-311 1.60415018e-311 6.95301688e-310
  1.60415018e-311 1.60414986e-311 1.60415018e-311 1.60415018e-311]
 [1.60415018e-311 1.60415018e-311 1.60415018e-311 1.60415018e-311
  1.60415018e-311 1.60415018e-311 6.95301688e-310 1.60415018e-311]]


In [ ]:
because uses garbage values 
old values

In [45]:
#create an array with random elements
arr1=np.random.randint(10,50,70)
print(arr1)

[13 24 44 13 36 21 13 32 49 20 49 12 25 10 29 26 45 34 15 27 25 42 10 34
 13 26 36 49 47 19 20 43 12 17 42 39 36 22 49 15 32 23 10 20 16 25 40 36
 34 20 12 49 20 25 23 42 36 34 11 28 25 44 32 31 11 41 17 13 40 40]


# Changing the shape of the array

In [46]:
arr1=np.random.randint(10,50,70).reshape(10,7)
print(arr1)

[[49 15 25 34 42 36 43]
 [22 35 32 45 39 40 10]
 [40 48 15 48 19 10 16]
 [48 37 12 17 46 32 41]
 [16 15 43 35 19 17 46]
 [45 36 10 16 22 20 11]
 [40 39 45 44 43 25 18]
 [42 12 14 30 16 16 46]
 [17 48 30 42 17 13 17]
 [22 26 41 11 48 28 27]]


In [47]:
arr1=np.random.randint(10,50,70)
arr1.reshape(7,10)

array([[38, 40, 26, 25, 47, 17, 45, 41, 41, 29],
       [13, 26, 31, 26, 19, 45, 41, 32, 49, 45],
       [20, 22, 38, 36, 24, 34, 29, 31, 22, 27],
       [27, 23, 37, 16, 14, 46, 27, 15, 37, 27],
       [12, 16, 11, 49, 21, 26, 42, 38, 17, 31],
       [39, 31, 25, 40, 47, 25, 46, 33, 34, 21],
       [36, 27, 14, 38, 31, 33, 17, 43, 36, 15]], dtype=int32)

In [48]:
arr2=np.random.randint(10,50,71)
arr2.reshape(71,)

array([33, 43, 24, 30, 43, 48, 19, 14, 43, 40, 45, 22, 24, 10, 30, 17, 18,
       33, 14, 38, 36, 33, 29, 34, 12, 15, 15, 32, 39, 15, 47, 11, 22, 18,
       36, 25, 18, 16, 33, 24, 29, 35, 31, 22, 39, 35, 16, 42, 44, 38, 12,
       49, 37, 46, 21, 22, 39, 38, 17, 25, 17, 28, 39, 40, 35, 30, 49, 32,
       11, 32, 23], dtype=int32)

In [49]:
# reshping by keeping any one dim as -ve values
arr1=np.random.randint(10,50,100)
arr1

array([27, 34, 21, 39, 27, 44, 29, 36, 44, 25, 30, 24, 21, 11, 19, 43, 43,
       23, 10, 18, 36, 16, 46, 48, 21, 40, 13, 47, 49, 47, 33, 23, 34, 22,
       42, 16, 12, 23, 39, 27, 21, 19, 16, 46, 28, 26, 47, 27, 35, 41, 17,
       45, 31, 32, 31, 44, 30, 24, 18, 13, 42, 35, 17, 14, 12, 49, 39, 34,
       45, 27, 13, 37, 32, 47, 42, 24, 30, 40, 41, 21, 35, 18, 16, 46, 15,
       11, 42, 47, 29, 47, 34, 38, 43, 39, 32, 38, 11, 23, 23, 36],
      dtype=int32)

In [56]:
# only one dim can be -ve
arr1.reshape(10,-5)

array([[27, 34, 21, 39, 27, 44, 29, 36, 44, 25],
       [30, 24, 21, 11, 19, 43, 43, 23, 10, 18],
       [36, 16, 46, 48, 21, 40, 13, 47, 49, 47],
       [33, 23, 34, 22, 42, 16, 12, 23, 39, 27],
       [21, 19, 16, 46, 28, 26, 47, 27, 35, 41],
       [17, 45, 31, 32, 31, 44, 30, 24, 18, 13],
       [42, 35, 17, 14, 12, 49, 39, 34, 45, 27],
       [13, 37, 32, 47, 42, 24, 30, 40, 41, 21],
       [35, 18, 16, 46, 15, 11, 42, 47, 29, 47],
       [34, 38, 43, 39, 32, 38, 11, 23, 23, 36]], dtype=int32)

In [57]:
arr1.reshape(5,4,-1)

array([[[27, 34, 21, 39, 27],
        [44, 29, 36, 44, 25],
        [30, 24, 21, 11, 19],
        [43, 43, 23, 10, 18]],

       [[36, 16, 46, 48, 21],
        [40, 13, 47, 49, 47],
        [33, 23, 34, 22, 42],
        [16, 12, 23, 39, 27]],

       [[21, 19, 16, 46, 28],
        [26, 47, 27, 35, 41],
        [17, 45, 31, 32, 31],
        [44, 30, 24, 18, 13]],

       [[42, 35, 17, 14, 12],
        [49, 39, 34, 45, 27],
        [13, 37, 32, 47, 42],
        [24, 30, 40, 41, 21]],

       [[35, 18, 16, 46, 15],
        [11, 42, 47, 29, 47],
        [34, 38, 43, 39, 32],
        [38, 11, 23, 23, 36]]], dtype=int32)

In [58]:
arr1

array([27, 34, 21, 39, 27, 44, 29, 36, 44, 25, 30, 24, 21, 11, 19, 43, 43,
       23, 10, 18, 36, 16, 46, 48, 21, 40, 13, 47, 49, 47, 33, 23, 34, 22,
       42, 16, 12, 23, 39, 27, 21, 19, 16, 46, 28, 26, 47, 27, 35, 41, 17,
       45, 31, 32, 31, 44, 30, 24, 18, 13, 42, 35, 17, 14, 12, 49, 39, 34,
       45, 27, 13, 37, 32, 47, 42, 24, 30, 40, 41, 21, 35, 18, 16, 46, 15,
       11, 42, 47, 29, 47, 34, 38, 43, 39, 32, 38, 11, 23, 23, 36],
      dtype=int32)

In [59]:
arr1=arr1.reshape(-5,10)
arr1

array([[27, 34, 21, 39, 27, 44, 29, 36, 44, 25],
       [30, 24, 21, 11, 19, 43, 43, 23, 10, 18],
       [36, 16, 46, 48, 21, 40, 13, 47, 49, 47],
       [33, 23, 34, 22, 42, 16, 12, 23, 39, 27],
       [21, 19, 16, 46, 28, 26, 47, 27, 35, 41],
       [17, 45, 31, 32, 31, 44, 30, 24, 18, 13],
       [42, 35, 17, 14, 12, 49, 39, 34, 45, 27],
       [13, 37, 32, 47, 42, 24, 30, 40, 41, 21],
       [35, 18, 16, 46, 15, 11, 42, 47, 29, 47],
       [34, 38, 43, 39, 32, 38, 11, 23, 23, 36]], dtype=int32)

In [60]:
# transpose
arr1.T

array([[27, 30, 36, 33, 21, 17, 42, 13, 35, 34],
       [34, 24, 16, 23, 19, 45, 35, 37, 18, 38],
       [21, 21, 46, 34, 16, 31, 17, 32, 16, 43],
       [39, 11, 48, 22, 46, 32, 14, 47, 46, 39],
       [27, 19, 21, 42, 28, 31, 12, 42, 15, 32],
       [44, 43, 40, 16, 26, 44, 49, 24, 11, 38],
       [29, 43, 13, 12, 47, 30, 39, 30, 42, 11],
       [36, 23, 47, 23, 27, 24, 34, 40, 47, 23],
       [44, 10, 49, 39, 35, 18, 45, 41, 29, 23],
       [25, 18, 47, 27, 41, 13, 27, 21, 47, 36]], dtype=int32)

In [61]:
# arithmatic operations on array performs the operation elementwise
arr1=np.random.randint(10,20,10)
print(arr1)

[18 16 18 18 18 10 14 19 18 12]


In [62]:
!pip install rich

In [63]:
from rich import print

In [64]:
# arithmatic operations on array performs the operation elementwise
arr1=np.random.randint(10,20,10)
print(arr1)

[12 10 17 18 12 14 13 19 11 19]

In [65]:
print(arr1+5)

[17 15 22 23 17 19 18 24 16 24]

In [66]:
print(arr1-5)
print(arr1*5)
print(arr1/5)
print(arr1//5)
print(arr1**5)
print(arr1%5)

[ 7  5 12 13  7  9  8 14  6 14]

[60 50 85 90 60 70 65 95 55 95]

[2.4 2.  3.4 3.6 2.4 2.8 2.6 3.8 2.2 3.8]

[2 2 3 3 2 2 2 3 2 3]

[ 248832  100000 1419857 1889568  248832  537824  371293 2476099  161051
 2476099]

[2 0 2 3 2 4 3 4 1 4]

In [67]:
print(arr1>5)
print(arr1<5)
print(arr1>=5)
print(arr1<=5)
print(arr1==5)
print(arr1!=5)

[ True  True  True  True  True  True  True  True  True  True]

[False False False False False False False False False False]

[ True  True  True  True  True  True  True  True  True  True]

[False False False False False False False False False False]

[False False False False False False False False False False]

[ True  True  True  True  True  True  True  True  True  True]

In [68]:
print(arr1 & 5)

#12 & 5 
#1100
#0101

#0100  4


[4 0 1 0 4 4 5 1 1 1]

In [69]:
# Dimension and shpae of the both array shoulb be same
arr1=np.random.randint(1,10,5)
arr2=np.random.randint(50,100,5)
print(arr1)
print(arr2)


[6 2 5 9 2]

[71 58 88 64 98]

In [71]:
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[ 77  60  93  73 100]

[-65 -56 -83 -55 -96]

[426 116 440 576 196]

In [72]:
print(arr1>arr2)
print(arr1<arr2)

[False False False False False]

[ True  True  True  True  True]

In [73]:
# vector product
#no of colums in first array and no of rows in 2nd array shoulb be same if its 2d array
#if it is 1d array the no of elements should be same 
#dimension of resultant arry=(no of rows in first arry, no of columns in 2nd array)

np.dot(arr1,arr2)

np.int32(1754)

In [74]:
#[6 2 5 9 2]
#[71 58 88 64 98]

(6*71)+(2*58)+(5*88)+(9*64)+(2*98)

1754

In [ ]:
rowsXcolums
3*3  3*2

3X3

[[a,b,c]  [[m,n]
 [d,e,f]   [p,q]
 [g,h,i]]  [r,s]]

[[(a*m)+(b*p)+(c*r), (a*n)+(b*q)+(c*s)],



 3X2